### ISSUE TITLE
Attestation DOS attack

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#128]
**Describe the attack**
A malicious attester can DOS a user by attesting many times in a single epoch, increasing the proving time of a UST significantly. There is no user input required to signup with an attester, the attester just gives and attestation with `signUp: 1`.

We could partially fix this by requiring that a user submit a zk proof confirming that they want to sign up with a certain attester. This would be verified onchain in the unirep signup function.

**Comment by vivianjeng** [comment]
So do we need to maintain an attesters list by ourselves (with an `admin` account)?
And we can also limit it by not sending zero attestation `(posRep: 0, negRep: 0, graffiti: 0, signUp:0)`
also adding `attestingFee` is another solution ( But now we haven't write a function to withdraw the `attestingFee` I think)
We can figure out how to make better use of `attestingFee`

**Comment by vimwitch** [comment]
> So do we need to maintain an attesters list by ourselves (with an admin account)?

I think no, we don't want the unirep contract controlled by an admin

>  And we can also limit it by not sending zero attestation (posRep: 0, negRep: 0, graffiti: 0, signUp:0)

I don't think this helps, a malicious attester could send `posRep: 1` at no extra cost.

I was thinking that to do a signup a user would need to provide a zk proof attesting to the attester id, or a nullifier or something. Just positive proof that the user allows attestations from an attester. 

> We can figure out how to make better use of attestingFee

Not sure about this. I kinda think we should remove this entirely. There's not much reason to have it. The only thing is calling the `beginEpochTransition` function which is sorta cheap. I just think having a fee for every attestation will not scale very well.

**Comment by vivianjeng** [comment]
> I think no, we don't want the unirep contract controlled by an admin

I remember that Barry doesn't want the attesters can easily sign up (and they might issue valueless token)
We can ask Barry about this
Also signing up a lot of attesters means we have to maintain a big user state tree
even if we want to do this we might not be able to generate proofs in frontend (because the circuit size should be large)
I think it would make the user experience bad
So my idea is that we either control a attester list or we use interep to sign up attesters (if they have gold level in some oauth app)

> I was thinking that to do a signup a user would need to provide a zk proof attesting to the attester id, or a nullifier or something. Just positive proof that the user allows attestations from an attester.

I am afraid that it contradicts the **non-repudiable** feature in unirep
if user has bad rep he can choose not to receive it

> We can figure out how to make better use of attestingFee

I mean `attestingFee` can prevent the attestation DOS attack. If attestation requires some cost, attesters cannot easily attack the system.
I mean it might not be used in `beginEpochTransition`. We can figure out how to benefit the users/attesters or it can be used in paying gas when calling unirep

**Comment by vimwitch** [comment]
>  Also signing up a lot of attesters means we have to maintain a big user state tree
It doesn't change the UST size for users unless they attest to them.

>  even if we want to do this we might not be able to generate proofs in frontend (because the circuit size should be large)
We could put a limit on the number of attesters a user can receive reputation from if this is a problem.

> I am afraid that it contradicts the non-repudiable feature in unirep
I think this is only once a user is signed up with an attester. I think it's acceptable for a user to refuse reputation from an attester that has not attested to them before.

> I mean attestingFee can prevent the attestation DOS attack. If attestation requires some cost, attesters cannot easily attack the system.
The problem is we don't know what to do with this fee, and if we set it high enough to deter an attacker then there are usability issues. The total fees would be much more than the gas fee in an epoch.
